#set text(font: "UbuntuMono Nerd Font")
#set par(justify: true) 
== Resolución del problema inverso de RUS (Espectroscopía de Resonancia Ultrasónica) en el caso cubico

== Alejandro Cubillos
=== Estudiante de maestría, Universidad de los Andes

En el seminario se describirá brevemente en qué consiste el problema de RUS y cómo esta técnica permite medir las constantes elásticas de un sólido. Estas constantes elásticas son de fundamental importancia debido a que están relacionadas directamente a la estructura atómica y diferentes propiedades térmicas del material. Además las constantes elásticas también pueden ser usadas para determinar la ecuación de estado de varias funciones termidinámicas #cite(<Leisure_1997>). La técnica de RUS consiste en colocar una muestra sólida entre 2 transductores piezoeléctricos, uno de ellos hace oscilar la mueastra en un rango de frecuencias y el otro detecta ciertas frecuencias en las que el sólido hace resonancia #cite(<Migliori_1993>). Estas frecuencias están relacionadas con las constantes elásticas mediante un problema de valores propios generalizado, cuyas matrices dependen de las constantes elásticas y los valores propios contienen la información de las frecuencias de resonancia. Obtener las frecuencias de resonancia a partir de las constantes elásticas resolviendo el problema de valores propios se conoce como problema directo o "forward problem". Sin embargo, en el laboratorio se obtienen las frecuencias de resonancia y hay que encontrar las constantes elásticas a partir de estas frecuencias. Este problema se conoce como el problema inverso o "inverse problem". Existe un método que permite resolver este problema inverso llamado el algoritmo de Levenber-Marquardt, el cual determina las constantes iterando varias veces el problema directo a partir de una souposición de valores iniciales de las constantes elásticas. El problema de este método está en que se requiere una muy buena inicialización de las constantes para poder resolver el problema, es decir, se requiere conocer de manera aproximada las constantes desde un principio #cite(<Fukuda_2023>). Además este método puede ser lento debido a la contidad de iteraciones del problema directo que puede llegar hacer. Por esta razón se buscó entrenar un modelo de machine learning que permita obtener las constantes elásticas a partir de las frecuencias en una sola iteración, el cual fue entrenado con multiples datos de problemas directos. En el presente seminario se describirá como se entrenó dicho modelo y como fue su desempeño obteniendo las constantes elásticas de distintos materiales. 

#bibliography("References.bib")
