#heading(level: 2, outlined: false, numbering: none)[Abstract]

The elastic constants of a solid, which relate strain and stress in generalized Hooke's law, are of fundamental importance, as they are directly related to the atomic structure of the solid and are connected to its thermal properties. One of the key applications of determining elastic constants is the detection of phase transitions in a solid at different temperatures and/or pressures. These constants are derived from the internal energy with respect to the atomic positions. For these reasons, experimental techniques that allow the determination of elastic constants have been a priority in solid-state physics and continuum mechanics. 

The technique on which this project focuses on is Resonant Ultrasound Spectroscopy (RUS), which measures the resonance frequencies of a solid. It consists of placing a solid sample between two piezoelectric transducers, where the first transducer excites the sample at different frequencies and the second receives the resonant response of the solid.

By formulating a Lagrangian that describes the oscillations within the RUS setup and applying the Rayleigh-Ritz method, where the displacements are expressed in terms of basis functions, a generalized eigenvalue problem, that relates the elastic constants to the frequencies, can be derived. In this problem, the matrices depend on the elastic constants, and the resonance frequencies appear among the eigenvalues. Determining the resonance frequencies, for the RUS method, from the elastic constants and the sample dimensions, by solving the eigenvalue problem, is known as the forward problem. On the other hand, determining the elastic constants from the measured frequencies and the sample dimensions is known as the inverse problem, which is the problem to be solved once the frequencies are measured in the laboratory. However, this is a complex problem to solve, as existing methods require a good initialization of the constants and significant computational time #cite(<Leisure_1997>).

The present project aims to create a solution to the inverse problem through the use of machine learning, focusing on solids with isotropic and cubic crystal structures. To achieve this, various variable transformations and operations between the problem’s features — namely, frequencies and sample dimensions — were proposed, as well as transformations of the targets, which are the elastic constants. All variables were modified in such a way that they would fall within defined ranges and become dimensionless. This allowed for the development of models capable of solving the problem regardless of the sample size or the scale of the elastic constants.

With a dataset of hundreds of thousands of entries, a sequential neural network model was implemented and trained. This model was capable of predicting the relationships between the elastic constants of a material based on the relationships between frequencies and the aspect ratios of the material. Then, the model was placed inside a pipeline that was able to predict the elastic constants based on the frequencies and the sample dimensions. 

This solution was tested with different materials having a cubic crystal structure and was compared with another model developed by Fukuda #cite(<Fukuda_2023>). The model proposed in this project proved to have a better prediction capacity having a MAPE (Mean Absolute Percentage Error) of 4.14% compared to Fukuda's model error of 5.16% for $C_11$ constant, 8.32% compared to Fukuda's model error of 10.90% for $C_12$, and 2.44% compared to Fukuda's model error of 7.78% for $C_44$. Also the solution proposed in the present project was capable of solving the inverse problem for any parallelepiped sample regardless of its dimensions. The present solution was able to predict elastic constants of cubic materials using only 20 frequencies while Fukuda's model used 100 frequencies. The training time of the present model was 9 hours with an AMD RX6600M GPU while Fukuda's model training time was 2 days with a Nvidia RTX 3090 GPU. Nonetheless, there are still improvements that could be made to the model, such as dividing it into different regions of aspect ratios and training a model for each region, searching for better variable modifications and extending the approach to the orthorhombic case, among others.
