#heading(level: 2, outlined: false, numbering: none)[Abstract]

The elastic constants of a solid are of fundamental importance, as they are directly related to the atomic structure of the material and are connected to its thermal properties. They also provide thermoelectric and piezoelectric information about the material. One of the key applications of determining elastic constants is the detection of phase transitions in a solid at different temperatures and/or pressures, since these constants are derived from the internal energy with respect to the atomic positions. For these reasons, experimental techniques that allow the determination of elastic constants have been a priority in solid-state physics.

The technique on which this project focuses is Resonant Ultrasound Spectroscopy (RUS), which measures the resonance frequencies of a solid. It consists of placing a solid sample between two piezoelectric transducers, where the first transducer excites the sample at different frequencies and the second receives the resonant response of the solid.

The elastic constants are related to the frequencies through a generalized eigenvalue equation, whose matrices depend on the constants, and where the frequencies appear among the eigenvalues. Determining the resonance frequencies from the elastic constants and the sample dimensions, by solving the eigenvalue problem, is known as the forward problem. On the other hand, determining the elastic constants from the measured frequencies and the sample dimensions is known as the inverse problem, which is the problem to be solved once the frequencies are measured in the laboratory. However, this is a complex problem to solve, as existing methods require a good initialization of the constants and significant computational time.

For this reason, the present project aims to create a solution to the inverse problem through the use of artificial intelligence, focusing on solids with a cubic crystal structure (including isotropic solids, as this is a particular case of the cubic structure). To achieve this, various variable transformations and operations between the problem’s features — namely, the frequencies and the material dimensions — were proposed, as well as transformations of the targets, which are the elastic constants, to simplify the problem. All variables were modified in such a way that they would fall within defined ranges and become dimensionless. This allowed for the development of models capable of solving the problem regardless of the sample size or the scale of the elastic constants.

With hundreds of thousands of modified-variable data points, a sequential neural network model was trained and implemented. This model was capable of predicting the relationships between the elastic constants of a material given the relationships between frequencies and the aspect ratio information of the material, or the relationships among its dimensions. Once the relationships between the constants were obtained from the model, the values of the elastic constants could be easily calculated analytically, using the experimental eigenvalues and the eigenvalues from a forward problem fed with arbitrary constants that satisfy the relationships predicted by the model.

This solution was tested with different materials having a cubic crystal structure and was compared with another model developed in 2023. The model proposed in this project not only proved to be simpler, but it was also capable of solving the inverse problem for any parallelepiped sample regardless of its dimensions, using fewer computational resources and fewer resonance frequencies. Nonetheless, there are still improvements that could be made to the model, such as dividing it into different regions according to geometries, adjusting the modified variables to have a more direct relationship with physical quantities such as Poisson's ratio, extending the approach to the orthorhombic case, among others.
