#heading(level: 2, outlined: false, numbering: none)[Abstract]

The elastic constants of a solid—quantities that relate stress and strain through the generalized Hooke's law—are of fundamental importance. These constants are directly linked to the atomic structure and thermodynamic behavior of materials. One of their key applications is the detection of phase transitions under varying temperature and pressure conditions. Since the elastic constants are derived from the internal energy with respect to atomic positions, experimental techniques that determine them have become essential in solid-state physics and continuum mechanics.

This project focuses on Resonant Ultrasound Spectroscopy, a technique that measures the resonance frequencies of a solid sample. The sample is placed between two piezoelectric transducers: one excites the sample at various frequencies, while the other detects its resonant response. By formulating a Lagrangian that describes the oscillatory behavior of the system and applying the Rayleigh–Ritz method, a generalized eigenvalue problem is obtained. In this formulation, the resonance frequencies appear as eigenvalues, and the matrices involved depend on the elastic constants and sample geometry. Solving this problem from known elastic constants is referred to as the forward problem, whereas inferring the elastic constants from measured frequencies and sample dimensions defines the inverse problem—the central challenge addressed in this work. Traditional approaches to the inverse problem often require a good initial guess and are computationally expensive.

This thesis proposes a machine learning–based solution to the inverse problem for isotropic and cubic solids, specifically those shaped as parallelepipeds. To do so, various physics-informed transformations were introduced to simplify the problem, making all variables dimensionless and bounded within finite ranges. These transformations were applied to both the input features (frequencies and sample dimensions) and the targets (elastic constants), enabling the model to generalize across different sample sizes and elastic regimes.

Using a dataset of hundreds of thousands of entries, sequential neural networks were trained to predict transformed elastic constants from the transformed features. These models were integrated into a pipeline capable of recovering the full elastic constants of a material based on its resonance frequencies and geometry.

The proposed solution was evaluated on multiple test materials and compared with a previous deep learning approach based on convolutional and residual neural networks, with dozens of layers. The present model demonstrated improved predictive performance, achieving lower Mean Absolute Percentage Errors across all three independent elastic constants of cubic solids, obtaining errors of 4.14% for $C_11$ constant, 8.31% for $C_12$ constant and 2.44% for $C_44$, while the previous approach obtained error of 5.15% for $C_11$ constant, 10.90% for $C_12$ constant and 7.78% for $C_44$. It also required significantly fewer frequencies (20 versus 100), less training time (9 hours versus 2 days), less computational power, and fewer training samples. Importantly, our method works for samples of arbitrary dimensions.

Although successful, the approach could be further improved by dividing the data space into different regions of aspect ratio or elastic constant regimes, training specialized models for each case, exploring improved variable transformations, and extending the methodology to more complex crystal structures such as orthorhombic systems.
