= Conclusions and Outlook <chap:conclusions_outlook>

In this work, a solution was successfully developed for the inverse problem in Resonant Ultrasound Spectroscopy (RUS), which consists of determining the elastic constants of a solid from its resonance frequencies and geometric dimensions. The method was designed to work with isotropic materials and solids with cubic crystal structure, specifically those shaped as parallelepipeds.

To achieve this, a code was implemented to solve the forward problem, which consists of calculating the resonance frequencies from the elastic constants and geometry of the solid. This is framed as a generalized eigenvalue problem, where the matrices are constructed using the elastic constants and the sample’s geometry. The method is based on an approximation using the Rayleigh–Ritz method, as detailed in @chap:forward.

Subsequently, various variable transformations and operations were applied both to the features (i.e., frequencies and dimensions of the solid) and the targets (i.e., elastic constants) to simplify the problem. All variables were transformed to be dimensionless and confined within well-defined finite ranges. This allowed the development of a general strategy or pipeline capable of solving the inverse problem regardless of the sample’s size or the magnitude of its elastic constants. This strategy is fully explained in @chap:transformations and summarized in @fig:diagram_inverse.

With the transformation strategy and the forward problem code in place, hundreds of thousands of data entries were generated to train neural network models—one for the isotropic case and another for the cubic case—capable of predicting the transformed targets. After training, the models were evaluated on independent test data and integrated into the complete pipeline. Finally, the pipeline’s ability to predict the elastic constants of various materials reported in the literature was assessed and compared with the model proposed by Fukuda et al #cite(<Fukuda_2023>). The pipeline developed in this work not only achieved lower Mean Absolute Error (MAE) than Fukuda et al's model, and better metrics in general, as shown in @table:Fukuda_comparison, @fig:box_plot_nonabs_error and @fig:box_plot_abs_error, but did so using significantly fewer computational resources, in less time, with less training data, and using fewer resonance frequencies (20 in this work versus 100 in Fukuda et al's model). Moreover, the solution developed here works regardless of the sample’s dimensions.

Nonetheless, several improvements can still be made. For example, the problem could be partitioned into multiple regions according to aspect ratio (i.e., the ratio between the sample’s dimensions) and different elastic constant regimes, with separate models trained for each region. Additionally, more effective variable transformations could be designed to simplify the models even further, or new data generation strategies could be explored to improve training efficiency. Finally, the approach presented here—based on transformed variables—could be extended to other crystal structures, such as orthorhombic solids. 
