= Conclusions and Outlook <chap:conclusions_outlook>

In this work, a solution was successfully developed for the inverse problem in Resonant Ultrasound Spectroscopy, which consists of determining the elastic constants of a solid from its resonance frequencies and geometric dimensions. The method was designed to work for isotropic materials and solids with cubic crystal structure, specifically those shaped as parallelepipeds.

To achieve this, a numerical solution to the forward problem was implemented. This problem involves calculating the resonance frequencies from the elastic constants and the geometry of the solid. It is framed as a generalized eigenvalue problem, where the matrices are constructed using the elastic constants and the sample’s geometry. The method is based on an approximation using the Rayleigh–Ritz method, as described in @chap:forward.

In @chap:failure, exploratory data analysis was carried out to examine the behavior, distributions, and correlations among the frequencies, dimensions, and elastic constants. Based on these insights, various variable transformations and operations were applied to both the features (i.e., frequencies and sample dimensions) and the targets (i.e., elastic constants) to simplify the problem. All variables were transformed to be dimensionless and confined within well-defined, finite ranges. This enabled the development of a general pipeline capable of solving the inverse problem regardless of the sample’s size or the magnitude of its elastic constants. The complete strategy is presented in @chap:transformations and summarized in @fig:diagram_inverse.

With the physics-informed variable transformations and the numerical forward problem solution in place, hundreds of thousands of data entries were generated to train neural network models—one for the isotropic case and another for the cubic case—capable of predicting the transformed targets. After training, the models were evaluated on independent test data and integrated into the complete pipeline. Finally, the pipeline’s performance in predicting the elastic constants of various materials reported in the literature was assessed and compared with the model proposed by Fukuda et al. #cite(<Fukuda_2023>)

The pipeline developed in this work achieved lower Mean Absolute Percentage Error than the model proposed by Fukuda et al. Specifically, this work achieved a Mean Absolute Percentage Error of 4.14% for the $C_11$ constant, 8.31% for $C_12$, and 2.44% for $C_44$, whereas Fukuda et al. reported errors of 5.15%, 10.90%, and 7.78% for the same constants, respectively. Standard deviations associated with these percentages can be found in @table:Fukuda_comparison.

Additionally, this work yielded better performance in terms of error distribution, as evidenced by the smaller box plots for both absolute and non-absolute errors compared to those of Fukuda et al., shown in @fig:box_plot_nonabs_error and @fig:box_plot_abs_error.

The model presented in this work accomplished these results using significantly fewer computational resources (an AMD Radeon RX6600M GPU, compared to Fukuda et al.'s Nvidia RTX 3090), shorter training time (9 hours vs. 2 days), less training data (656,414 entries vs. 3,672,000), and fewer resonance frequencies (20 vs. 100). Moreover, the solution works for samples of any dimension, whereas Fukuda et al.'s model was tailored to a specific shape.

Nonetheless, several improvements could further enhance the pipeline. For instance, the problem could be divided into multiple regions based on aspect ratio (i.e., the ratios between sample dimensions) and elastic constant regimes, with a separate model trained for each region. More effective variable transformations could be designed to simplify the models even further. New data generation strategies—such as generating data based on compositional fractions—could also be explored to improve training efficiency. Lastly, the approach presented here, based on physics-informed transformed variables, could be extended to other crystal structures (such as orthorhombic solids) by identifying thermodynamic stability constraints and constructing new variables accordingly, as was done for the cubic case in this work.
